name: open_settings
description: The most complete flutter plugin packages for open various settings screen in Android and Ios
version: 1.0.2
author: "Ali Hoseinpoor <iamhoseinpoor@gmail.com>"
homepage: https://github.com/AliHoseinpoor/open_settings

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.12.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: alihoseinpoor.com.open_settings
        pluginClass: OpenSettingsPlugin
      ios:
        pluginClass: OpenSettingsPlugin

#flutter:
#  plugin:
#    androidPackage: alihoseinpoor.com.open_settings
#    pluginClass: OpenSettingsPlugin
